name: Pack Conversion
description: Request an automated pack conversion
title: "[Pack]: "
labels: ["conversion"]

body:
  - type: markdown
    attributes:
      value: |
        Please include a directly downloadable link to your pack.

  - type: input
    id: java-pack-direct-download-url
    attributes:
      label: Java Pack Direct Download URL
      placeholder: https://example.com/pack.zip
    validations:
      required: true

  - type: input
    id: default-pack-direct-download-url
    attributes:
      label: Default Pack Direct Download URL
      placeholder: (optional)
    validations:
      required: false

  - type: input
    id: bedrock-merge-pack-direct-download-url
    attributes:
      label: Bedrock Merge Pack Direct Download URL
      placeholder: (optional)
    validations:
      required: false

  - type: dropdown
    id: default-assets-version
    attributes:
      label: Default Assets Version
      options:
        - "1.19.3"
        - "1.20.1"
    validations:
      required: false

  - type: dropdown
    id: block-material
    attributes:
      label: Block Material
      options:
        - alpha_test
        - opaque
        - blend
        - double_sided
    validations:
      required: false

  - type: dropdown
    id: attachable-material
    attributes:
      label: Attachable Material
      options:
        - entity_alphatest_one_sided
        - entity
        - entity_alphatest
        - entity_alphablend
        - entity_emissive_alpha_one_sided
    validations:
      required: false

  # Default TRUE options
  - type: dropdown
    id: archive-scratch-files
    attributes:
      label: Archive Scratch Files
      options:
        - "true"
        - "false"
    validations:
      required: false

  - type: dropdown
    id: rename-model-files
    attributes:
      label: Rename Model Files
      options:
        - "true"
        - "false"

  - type: dropdown
    id: font-conversion
    attributes:
      label: Font Conversion
      options:
        - "true"
        - "false"

  - type: dropdown
    id: armor-conversion
    attributes:
      label: Armor Conversion
      options:
        - "true"
        - "false"

  - type: dropdown
    id: meg3-fix
    attributes:
      label: MEG3 Fix
      options:
        - "true"
        - "false"

  - type: dropdown
    id: sounds-conversion
    attributes:
      label: Sounds Conversion
      options:
        - "true"
        - "false"

  - type: dropdown
    id: bow-conversion
    attributes:
      label: Bow Conversion
      options:
        - "true"
        - "false"

  - type: dropdown
    id: shield-conversion
    attributes:
      label: Shield Conversion
      options:
        - "true"
        - "false"

  - type: dropdown
    id: block-conversion
    attributes:
      label: Block Conversion
      options:
        - "true"
        - "false"

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      options:
        - label: I agree to follow the Code of Conduct
          required: true
